export * from './schemas/atributos-valores/tabela';
export * from './schemas/atributos/tabela';
export * from './schemas/categorias/tabela';
export * from './schemas/categorias_produtos/tabela';
export * from './schemas/imagens/tabela';
export * from './schemas/pedidos-itens/tabela';
export * from './schemas/pedidos/tabela';
export * from './schemas/produtos/tabela';
export * from './schemas/variantes/tabela';

export * from './schemas/atributos-valores/relacoes';
export * from './schemas/atributos/relacoes';
export * from './schemas/categorias/relacoes';
export * from './schemas/categorias_produtos/relacoes';
export * from './schemas/imagens/relacoes';
export * from './schemas/pedidos-itens/relacoes';
export * from './schemas/pedidos/relacoes';
export * from './schemas/produtos/relacoes';
export * from './schemas/variantes/relacoes';
